use_frameworks!

target 'UnlimitBar_Example' do
  pod 'UnlimitBar', :path => '../'
  pod 'SnapKit'
  target 'UnlimitBar_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  pod 'FBSnapshotTestCase' , '~> 2.1.4'
  pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
